const SITE_CONFIG={name:"Twins Kitchen & Bakery World",email:"Ikegodsunday@gmail.com",phoneDisplay:"08033231712",whatsappNumber:"2348033231712",address:"Alaba International Market, Nigeria",hours:"Open 24 hours",catalogueMode:"demo",priceLabel:"Current price on request",mapsUrl:"https://www.google.com/maps/search/?api=1&query=Alaba+International+Market",whatsappUrl:"https://wa.me/2348033231712"};
const P=[
{id:1,n:"Commercial 6-Burner Stainless Range",c:"Cooking Equipment",p:null,i:"https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1000&q=85",tag:"Popular",desc:"Heavy-duty cooking range for busy commercial kitchens.",spec:"6 burners · stainless body · commercial duty"},
{id:2,n:"Professional Spiral Dough Mixer",c:"Bakery Equipment",p:null,i:"https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1000&q=85",tag:"Bakery",desc:"Production-focused mixer for bread and dough preparation.",spec:"Spiral mixing · bakery production · heavy duty"},
{id:3,n:"Commercial Convection Oven",c:"Bakery Equipment",p:null,i:"https://images.unsplash.com/photo-1585659722983-3a675dabf23d?auto=format&fit=crop&w=1000&q=85",tag:"Featured",desc:"Versatile commercial oven for consistent baking and cooking.",spec:"Convection · commercial use · production oven"},
{id:4,n:"Stainless Steel Work Table",c:"Kitchen Equipment",p:null,i:"https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1000&q=85",tag:"Essential",desc:"Durable prep surface for professional food operations.",spec:"Stainless steel · prep station · easy clean"},
{id:5,n:"Commercial Upright Refrigerator",c:"Cold Storage",p:null,i:"https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=1000&q=85",tag:"Cold Storage",desc:"Large-format cold storage for restaurants and hospitality.",spec:"Upright format · commercial refrigeration"},
{id:6,n:"Planetary Cake Mixer",c:"Bakery Equipment",p:null,i:"https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1000&q=85",tag:"Popular",desc:"Multi-purpose mixer for cakes, creams and pastry work.",spec:"Planetary mixing · bakery · pastry"},
{id:7,n:"Commercial Stainless Sink Station",c:"Kitchen Equipment",p:null,i:"https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1000&q=85",tag:"Essential",desc:"Commercial washing and cleaning station.",spec:"Stainless steel · wash station"},
{id:8,n:"Restaurant Dining Chair Set",c:"Restaurant & Hotel",p:null,i:"https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1000&q=85",tag:"Front of House",desc:"Guest seating for restaurants, hotels and hospitality spaces.",spec:"Dining · hospitality · seating"},
{id:9,n:"Commercial Gas Fryer",c:"Cooking Equipment",p:null,i:"https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1000&q=85",tag:"Popular",desc:"High-output fryer for fast food and commercial kitchens.",spec:"Commercial frying · high output"},
{id:10,n:"Bakery Display Counter",c:"Bakery Equipment",p:null,i:"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=85",tag:"Display",desc:"Front-of-house display solution for bakery products.",spec:"Display · bakery · customer-facing"},
{id:11,n:"Commercial Blender Bar Station",c:"Bar & Beverage",p:null,i:"https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=1000&q=85",tag:"Beverage",desc:"Blend and prepare drinks efficiently in a beverage operation.",spec:"Beverage · bar · commercial blender"},
{id:12,n:"Heavy-Duty Storage Rack",c:"Storage",p:null,i:"https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1000&q=85",tag:"Storage",desc:"Organized storage for equipment, ingredients and supplies.",spec:"Heavy duty · storage · shelving"},
{id:13,n:"Commercial Deep Freezer",c:"Cold Storage",p:null,i:"https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=1000&q=85",tag:"Cold Storage",desc:"Dedicated frozen storage for high-volume food operations.",spec:"Freezer · commercial · bulk storage"},
{id:14,n:"Electric Food Warmer",c:"Serving Equipment",p:null,i:"https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1000&q=85",tag:"Service",desc:"Keep prepared food ready for service.",spec:"Food holding · service · commercial"},
{id:15,n:"Commercial Meat Slicer",c:"Food Preparation",p:null,i:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85",tag:"Prep",desc:"Efficient slicing equipment for professional food prep.",spec:"Food prep · slicing · commercial"},
{id:16,n:"Stainless Steel Extraction Hood",c:"Ventilation",p:null,i:"https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1000&q=85",tag:"Kitchen",desc:"Ventilation equipment for professional cooking areas.",spec:"Kitchen ventilation · extraction"},
{id:17,n:"Commercial Coffee Machine",c:"Bar & Beverage",p:null,i:"https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1000&q=85",tag:"Coffee",desc:"Coffee service equipment for cafés, hotels and restaurants.",spec:"Coffee · beverage · hospitality"},
{id:18,n:"Bakery Proofing Cabinet",c:"Bakery Equipment",p:null,i:"https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1000&q=85",tag:"Bakery",desc:"Controlled proofing support for bakery production.",spec:"Proofing · bakery · production"},
{id:19,n:"Commercial Ice Maker",c:"Cold Storage",p:null,i:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85",tag:"Hospitality",desc:"Ice production for restaurants, bars and hospitality.",spec:"Ice production · hospitality"},
{id:20,n:"Catering Service Trolley",c:"Catering Supplies",p:null,i:"https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1000&q=85",tag:"Catering",desc:"Mobile service support for catering and events.",spec:"Catering · transport · service"},
{id:21,n:"Commercial Shawarma Grill",c:"Cooking Equipment",p:null,i:"https://images.unsplash.com/photo-1528712306091-ed0763094c98?auto=format&fit=crop&w=1000&q=85",tag:"Popular",desc:"Dedicated grilling equipment for shawarma and high-volume service.",spec:"Gas cooking · commercial grill · service line"},
{id:22,n:"Heavy-Duty Gas Griddle",c:"Cooking Equipment",p:null,i:"https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1000&q=85",tag:"Cooking",desc:"Large cooking surface for breakfast, burgers and fast-service menus.",spec:"Gas griddle · heavy duty · high output"},
{id:23,n:"Commercial Pizza Oven",c:"Cooking Equipment",p:null,i:"https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=1000&q=85",tag:"Pizza",desc:"Production oven for pizza, flatbreads and high-temperature cooking.",spec:"Commercial oven · pizza · high temperature"},
{id:24,n:"Commercial Microwave Oven",c:"Cooking Equipment",p:null,i:"https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?auto=format&fit=crop&w=1000&q=85",tag:"Kitchen",desc:"Fast heating and finishing support for professional foodservice.",spec:"Commercial microwave · fast heating"},
{id:25,n:"Commercial Food Processor",c:"Food Preparation",p:null,i:"https://images.unsplash.com/photo-1598514982901-ae627a7b5f1a?auto=format&fit=crop&w=1000&q=85",tag:"Prep",desc:"High-throughput processing support for chopping, mixing and preparation.",spec:"Food processing · commercial prep"},
{id:26,n:"Commercial Vegetable Cutter",c:"Food Preparation",p:null,i:"https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1000&q=85",tag:"Prep",desc:"Consistent vegetable preparation for busy kitchens and catering operations.",spec:"Vegetable prep · cutting · commercial"},
{id:27,n:"Commercial Juice Extractor",c:"Bar & Beverage",p:null,i:"https://images.unsplash.com/photo-1622597467836-f3285f2131b8?auto=format&fit=crop&w=1000&q=85",tag:"Beverage",desc:"Fresh juice preparation equipment for cafés, bars and hospitality.",spec:"Juice extraction · beverage · commercial"},
{id:28,n:"Display Chiller Cabinet",c:"Cold Storage",p:null,i:"https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=1000&q=85",tag:"Display",desc:"Chilled presentation for drinks, desserts and ready-to-serve products.",spec:"Chilled display · refrigeration · customer-facing"},
{id:29,n:"Commercial Chest Freezer",c:"Cold Storage",p:null,i:"https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=1000&q=85",tag:"Cold Storage",desc:"Bulk frozen storage for foodservice operations.",spec:"Chest freezer · frozen storage · commercial"},
{id:30,n:"Commercial Ice Cream Machine",c:"Bar & Beverage",p:null,i:"https://images.unsplash.com/photo-1570197788417-0e82375c9371?auto=format&fit=crop&w=1000&q=85",tag:"Dessert",desc:"Commercial frozen dessert production for cafés, restaurants and dessert counters.",spec:"Frozen dessert · commercial production"},
{id:31,n:"Stainless Wall Shelf",c:"Storage",p:null,i:"https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1000&q=85",tag:"Storage",desc:"Wall-mounted storage for tools, containers and kitchen supplies.",spec:"Stainless steel · wall storage"},
{id:32,n:"Stainless Steel Wall Cabinet",c:"Storage",p:null,i:"https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1000&q=85",tag:"Storage",desc:"Enclosed wall storage for organised commercial kitchen work areas.",spec:"Stainless steel · enclosed storage"},
{id:33,n:"Commercial Dishwasher",c:"Kitchen Equipment",p:null,i:"https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1000&q=85",tag:"Cleaning",desc:"Commercial dishwashing support for restaurants and hospitality operations.",spec:"Commercial washing · high throughput"},
{id:34,n:"Stainless Hand Wash Sink",c:"Kitchen Equipment",p:null,i:"https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1000&q=85",tag:"Essential",desc:"Dedicated hand-washing station for professional food environments.",spec:"Stainless steel · hand wash · hygiene"},
{id:35,n:"Banquet Folding Table",c:"Restaurant & Hotel",p:null,i:"https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1000&q=85",tag:"Hospitality",desc:"Flexible event and banquet table solution for hospitality spaces.",spec:"Banquet · folding · hospitality"},
{id:36,n:"Stainless Chafing Dish Set",c:"Serving Equipment",p:null,i:"https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1000&q=85",tag:"Service",desc:"Food-holding and presentation equipment for events and buffet service.",spec:"Buffet service · food holding · stainless"},
{id:37,n:"Glass Food Display Warmer",c:"Serving Equipment",p:null,i:"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=85",tag:"Display",desc:"Warm display support for prepared foods in customer-facing service areas.",spec:"Heated display · food holding · service"},
{id:38,n:"Commercial Coffee Grinder",c:"Bar & Beverage",p:null,i:"https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1000&q=85",tag:"Coffee",desc:"Grinding support for cafés and professional coffee service.",spec:"Coffee grinding · café · beverage"},
{id:39,n:"Bakery Dough Sheeter",c:"Bakery Equipment",p:null,i:"https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1000&q=85",tag:"Bakery",desc:"Production dough handling for bakeries, pastry kitchens and food businesses.",spec:"Dough sheeting · bakery production"},
{id:40,n:"Commercial Spiral Mixer",c:"Bakery Equipment",p:null,i:"https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1000&q=85",tag:"Bakery",desc:"Heavy-duty spiral mixing for higher-volume dough production.",spec:"Spiral mixing · commercial bakery · heavy duty"}
];
const C=[
["Cooking Equipment","High-output cooking, ranges, fryers and hot-line equipment.","https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=900&q=80"],
["Bakery Equipment","Mixers, ovens, proofing and bakery production equipment.","https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=80"],
["Kitchen Equipment","Prep stations, sinks, utensils and kitchen infrastructure.","https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=900&q=80"],
["Cold Storage","Refrigerators, freezers and cold-chain equipment.","https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=900&q=80"],
["Restaurant & Hotel","Front-of-house, seating and hospitality equipment.","https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=900&q=80"],
["Bar & Beverage","Coffee, blending, drink preparation and beverage service.","https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80"],
["Food Preparation","Slicing, mixing, cutting and preparation workflow equipment.","https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80"],
["Storage","Shelving, racks and operational storage solutions.","https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=900&q=80"],
["Serving Equipment","Food holding, service stations and front-of-house support.","https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=900&q=80"],
["Catering Supplies","Equipment for mobile kitchens, events and catering operations.","https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=900&q=80"],
["Ventilation","Extraction and climate-control support for working kitchens.","https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=900&q=80"]
];
const B=[
["Restaurant","Hot line · prep · cold storage · service","Cooking Equipment","Cold Storage","Food Preparation","Serving Equipment"],
["Bakery","Mixing · proofing · baking · display","Bakery Equipment","Cold Storage","Storage","Serving Equipment"],
["Hotel","Kitchen · breakfast · beverage · guest service","Cooking Equipment","Restaurant & Hotel","Bar & Beverage","Cold Storage"],
["Catering Business","Mobile prep · cooking · transport · service","Cooking Equipment","Food Preparation","Catering Supplies","Serving Equipment"],
["Bar / Lounge","Beverage · ice · chilling · service","Bar & Beverage","Cold Storage","Restaurant & Hotel","Serving Equipment"],
["Café","Coffee · pastry · refrigeration · front of house","Bar & Beverage","Bakery Equipment","Cold Storage","Restaurant & Hotel"]
];
const KITCHEN_PACKAGES=[
{id:"restaurant-starter",name:"Restaurant Starter Kitchen",type:"Restaurant",size:"Starter operation",intro:"A planning bundle for a restaurant that needs the core cooking, preparation, storage and service workflow.",ids:[1,4,5,9,14,15],note:"Demo planning package — confirm exact equipment, dimensions, fuel/power and current pricing with Twins."},
{id:"bakery-production",name:"Bakery Production Setup",type:"Bakery",size:"Production-focused",intro:"A bakery workflow built around mixing, baking, proofing, cold storage and customer-facing display.",ids:[2,3,5,6,10,18],note:"Demo planning package — final bakery setup should be sized around production volume and available space."},
{id:"cafe-launch",name:"Café Launch Package",type:"Café",size:"Compact operation",intro:"A café-oriented starting list connecting beverage service, pastry support, refrigeration and front-of-house needs.",ids:[4,5,6,8,17,19],note:"Demo planning package — confirm electrical requirements, capacity and layout before purchase."},
{id:"bar-lounge",name:"Bar & Lounge Setup",type:"Bar / Lounge",size:"Service-focused",intro:"A beverage and hospitality package covering chilling, ice, blending and guest service.",ids:[5,8,11,13,19,14],note:"Demo planning package — ice, refrigeration and service capacity should be matched to expected demand."},
{id:"catering-mobile",name:"Catering Business Setup",type:"Catering Business",size:"Mobile / events",intro:"A flexible catering list focused on cooking, preparation, holding and movement between service locations.",ids:[1,9,15,14,20,12],note:"Demo planning package — transport, venue access and power/fuel availability should be confirmed for each job."}
];

const PRODUCT_DETAIL_DEFAULTS={
"Cooking Equipment":{material:"Stainless steel / model dependent",capacity:"Confirm exact model capacity",utility:"Confirm gas or electrical requirement",dimensions:"Confirm exact model dimensions",installation:"Confirm ventilation, gas/electrical and clearance requirements"},
"Bakery Equipment":{material:"Food-service construction / model dependent",capacity:"Confirm production capacity",utility:"Confirm electrical requirement",dimensions:"Confirm exact model dimensions",installation:"Confirm power, clearance and workflow requirements"},
"Kitchen Equipment":{material:"Stainless steel / model dependent",capacity:"Confirm working capacity",utility:"Confirm water, drainage or electrical requirements where applicable",dimensions:"Confirm exact model dimensions",installation:"Confirm plumbing, clearance and access requirements"},
"Cold Storage":{material:"Commercial refrigeration construction",capacity:"Confirm internal volume and temperature range",utility:"Confirm electrical requirement",dimensions:"Confirm exact model dimensions",installation:"Confirm ventilation, clearance and delivery access"},
"Restaurant & Hotel":{material:"Commercial hospitality construction / model dependent",capacity:"Confirm seating or service capacity",utility:"Confirm applicable site requirements",dimensions:"Confirm exact model dimensions",installation:"Confirm layout, access and installation requirements"},
"Bar & Beverage":{material:"Commercial beverage-service construction",capacity:"Confirm output or holding capacity",utility:"Confirm electrical, water or drainage requirements where applicable",dimensions:"Confirm exact model dimensions",installation:"Confirm counter, clearance and utility requirements"},
"Food Preparation":{material:"Food-service construction / model dependent",capacity:"Confirm processing capacity",utility:"Confirm electrical requirement where applicable",dimensions:"Confirm exact model dimensions",installation:"Confirm workspace, clearance and access requirements"},
"Storage":{material:"Stainless steel / commercial storage construction",capacity:"Confirm load or storage capacity",utility:"No dedicated utility unless model requires it",dimensions:"Confirm exact model dimensions",installation:"Confirm wall, floor or access requirements"},
"Serving Equipment":{material:"Commercial service construction / model dependent",capacity:"Confirm holding or service capacity",utility:"Confirm electrical requirement where applicable",dimensions:"Confirm exact model dimensions",installation:"Confirm service-space and access requirements"},
"Catering Supplies":{material:"Commercial catering construction / model dependent",capacity:"Confirm service or transport capacity",utility:"Confirm utility requirements for exact unit",dimensions:"Confirm exact model dimensions",installation:"Confirm transport, access and setup requirements"},
"Ventilation":{material:"Stainless steel / model dependent",capacity:"Confirm extraction capacity",utility:"Confirm electrical and ducting requirements",dimensions:"Confirm exact model dimensions",installation:"Professional site and ventilation assessment required"}
};
P.forEach(function(p){p.details=Object.assign({},PRODUCT_DETAIL_DEFAULTS[p.c]||{},p.details||{});p.media=Object.assign({images:[p.i],video:"",source:"temporary catalogue visual"},p.media||{});});
const MEDIA_LIBRARY=[
{id:"twins-bread-display",type:"image",title:"Twins bakery bread display",category:"Bakery Equipment",src:"assets/media/twins-bakery-bread-display.jpg",alt:"Bakery bread display supplied by Twins"},
{id:"twins-cake-display",type:"image",title:"Twins cake display counter",category:"Bakery Equipment",src:"assets/media/twins-cake-display-counter.jpg",alt:"Cake display counter supplied by Twins"},
{id:"twins-video-01",type:"video",title:"Twins bakery media · 01",category:"Bakery Equipment",src:"assets/media/twins-media-video-01.mp4",poster:"assets/media/twins-bakery-bread-display.jpg",alt:"Twins bakery media video 01"},
{id:"twins-video-02",type:"video",title:"Twins bakery media · 02",category:"Bakery Equipment",src:"assets/media/twins-media-video-02.mp4",poster:"assets/media/twins-cake-display-counter.jpg",alt:"Twins bakery media video 02"},
{id:"twins-video-03",type:"video",title:"Twins bakery media · 03",category:"Bakery Equipment",src:"assets/media/twins-media-video-03.mp4",poster:"assets/media/twins-bakery-bread-display.jpg",alt:"Twins bakery media video 03"},
{id:"kitchen",type:"image",title:"Commercial kitchen environment",category:"Cooking Equipment",src:"https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1800&q=90",alt:"Commercial kitchen"},
{id:"bakery",type:"image",title:"Bakery production environment",category:"Bakery Equipment",src:"https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1800&q=90",alt:"Bakery production"},
{id:"prep",type:"image",title:"Professional preparation workspace",category:"Kitchen Equipment",src:"https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1800&q=90",alt:"Kitchen preparation"},
{id:"service",type:"image",title:"Restaurant service environment",category:"Restaurant & Hotel",src:"https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1800&q=90",alt:"Restaurant service"},
{id:"coffee",type:"image",title:"Café beverage environment",category:"Bar & Beverage",src:"https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1800&q=90",alt:"Coffee service"},
{id:"prep-food",type:"image",title:"Food preparation workflow",category:"Food Preparation",src:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1800&q=90",alt:"Food preparation"}
];
const PROJECT_STAGES=["Idea / research","Site preparation","Equipment selection","Quotation stage","Ready to purchase","Replacing equipment"];
