function marketSafe(v){return String(v==null?"":v).replace(/[&<>"]/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[c]})}
async function marketApi(path,options){return apiRequest(path,options)}
async function currentAccount(){try{return (await marketApi('/api/account/me')).user}catch(e){return null}}
function marketMoney(v,c){if(v==null)return "Price on request";return (c||"NGN")==="NGN"?"₦"+Number(v).toLocaleString("en-NG"):(c||"")+" "+Number(v).toLocaleString()}
async function marketplace(){
var root=document.getElementById("marketplace");if(!root)return;
var cats=MARKETPLACE_CATEGORIES.map(function(c){return '<a class="marketcat" href="marketplace.html?category='+encodeURIComponent(c)+'"><b>'+marketSafe(c)+'</b><span>Browse community listings</span></a>'}).join("");
var q=new URLSearchParams(location.search).get("category")||"",data={listings:[]};
try{data=await marketApi('/api/marketplace/listings'+(q?'?category='+encodeURIComponent(q):''))}catch(e){}
var visible=data.listings||[];
root.innerHTML=head()+'<main class="page"><section class="marketHero"><div class="wrap marketHeroGrid"><div><span class="eyebrow">TWINS MARKETPLACE</span><h1>More than our own catalogue.</h1><p>Discover approved community listings alongside the official Twins catalogue.</p><div class="heroactions"><a class="btn red" href="sell-on-twins.html">Sell on Twins →</a><a class="btn light" href="products.html">Shop official Twins stock</a></div></div><div class="marketTrust"><b>OFFICIAL TWINS</b><span>Our catalogue</span><b>COMMUNITY MARKET</b><span>Seller-submitted listings</span><b>MODERATED</b><span>Listings reviewed before publication</span></div></div></section><section class="section"><div class="wrap"><div class="sectionhead"><div><span class="eyebrow darkey">EXPLORE</span><h2>Marketplace areas.</h2></div><p class="muted">Community listings remain separate from official Twins inventory.</p></div><div class="marketcats">'+cats+'</div></div></section><section class="section soft"><div class="wrap"><div class="sectionhead"><div><span class="eyebrow darkey">COMMUNITY LISTINGS</span><h2>'+(visible.length?"Latest approved listings":"No approved community listings yet")+'</h2></div><a class="btn light" href="seller-dashboard.html">Seller Hub →</a></div>'+(visible.length?'<div class="grid">'+visible.map(function(x){var m=x.media&&x.media[0];return '<article class="card marketcard">'+(m?'<img src="'+marketSafe(m.url)+'" alt="'+marketSafe(x.title)+'" loading="lazy">':'<div class="sellerPreview"></div>')+'<div class="cardbody"><span class="realbadge">COMMUNITY SELLER</span><h3>'+marketSafe(x.title)+'</h3><p class="muted">'+marketSafe(x.category)+' · '+marketSafe(x.location||"Location not specified")+'</p><p>'+marketSafe(x.description)+'</p><b>'+marketMoney(x.price,x.currency)+'</b><p class="small muted">Seller: '+marketSafe(x.seller)+'</p><a class="btn light mini" href="marketplace-listing.html?id='+encodeURIComponent(x.id)+'">View listing →</a></div></article>'}).join("")+'</div>':'<div class="empty"><h2>The community side is ready for its first approved sellers.</h2><p class="muted">Listings become public only after server-side review.</p><a class="btn red" href="sell-on-twins.html">Create a seller listing →</a></div>')+'</div></section><section class="section"><div class="wrap marketSteps"><article><b>01</b><h3>Create</h3><p>Prepare the product, photos, description, location and price preference.</p></article><article><b>02</b><h3>Review</h3><p>Twins checks the listing before publication.</p></article><article><b>03</b><h3>Discover</h3><p>Customers browse approved community products separately from official stock.</p></article><article><b>04</b><h3>Enquire</h3><p>Marketplace enquiries remain separate from official Twins catalogue orders.</p></article></div></section></main>'+foot()+'<div id="toast"></div>';
}
async function marketplaceListingPage(){
var root=document.getElementById("marketlisting");if(!root)return;var id=new URLSearchParams(location.search).get("id");if(!id){location.href="marketplace.html";return}
try{var x=(await marketApi("/api/marketplace/listings/"+encodeURIComponent(id))).listing,m=x.media||[];root.innerHTML=head()+'<main class="page"><div class="wrap"><div class="crumb"><a href="marketplace.html">Marketplace</a> / '+marketSafe(x.title)+'</div><section class="p3product"><div class="p3gallery panel"><div class="p3media">'+(m.length?'<img src="'+marketSafe(m[0].url)+'" alt="'+marketSafe(x.title)+'">':'<div class="sellerPreview"></div>')+'</div></div><div class="p3info"><span class="eyebrow darkey">COMMUNITY SELLER · '+marketSafe(x.category)+'</span><h1>'+marketSafe(x.title)+'</h1><p class="p3lead">'+marketSafe(x.description)+'</p><div class="p3quote"><span>Price</span><strong>'+marketMoney(x.price,x.currency)+'</strong><small>Confirm final terms directly with the seller. This is not an official Twins catalogue product.</small></div><div class="p3facts"><div><b>Seller</b><span>'+marketSafe(x.seller)+'</span></div><div><b>Location</b><span>'+marketSafe(x.location||"Not specified")+'</span></div><div><b>Seller verification</b><span>'+marketSafe(x.sellerVerification)+'</span></div></div><button class="btn red" onclick="requestMarketplaceOrder(\''+marketSafe(x.id)+'\')">Request order</button><button class="btn light" onclick="reportMarketplaceListing(\''+marketSafe(x.id)+'\')">Report listing</button></div></section></div></main>'+foot()+'<div id="toast"></div>';}catch(e){root.innerHTML=head()+'<main class="page"><div class="wrap"><div class="empty"><h2>Listing unavailable</h2><p class="muted">'+marketSafe(e.message||"This listing is no longer public.")+'</p><a class="btn red" href="marketplace.html">Back to Marketplace</a></div></div></main>'+foot()}}
async function requestMarketplaceOrder(id){var name=prompt("Your name:");if(!name)return;var phone=prompt("Your phone number:");if(!phone)return;var qty=Number(prompt("Quantity:","1")||1);if(!Number.isInteger(qty)||qty<1){toast("Enter a valid quantity");return}try{var r=await marketApi("/api/marketplace/listings/"+encodeURIComponent(id)+"/order-request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({buyerName:name,buyerPhone:phone,quantity:qty})});toast("Order request "+r.order.reference+" submitted. Payment is not enabled yet.");}catch(e){toast(e.message||"Could not submit order request")}}
async function reportMarketplaceListing(id){var reason=prompt("Reason for reporting this listing:");if(!reason)return;try{await marketApi("/api/marketplace/listings/"+encodeURIComponent(id)+"/report",{method:"POST",body:JSON.stringify({reason:reason})});toast("Report submitted")}catch(e){toast(e.message||"Could not submit report")}}
async function sellOnTwins(){
var root=document.getElementById("sell");if(!root)return;var user=await currentAccount(),cats=MARKETPLACE_CATEGORIES.map(function(c){return "<option>"+marketSafe(c)+"</option>"}).join("");
if(!user){root.innerHTML=head()+'<main class="page"><section class="marketHero compact"><div class="wrap"><span class="eyebrow">SELL ON TWINS</span><h1>Seller access starts with an account.</h1><p>Sign in or create a Twins account before submitting a marketplace listing.</p><a class="btn red" href="login.html">Sign in / Create account →</a></div></section></main>'+foot();return}
root.innerHTML=head()+'<main class="page"><section class="marketHero compact"><div class="wrap"><span class="eyebrow">SELL ON TWINS</span><h1>Turn your product into a proper listing.</h1><p>Photos are uploaded to managed server storage. Every listing enters moderation before publication.</p></div></section><section class="section"><div class="wrap sellerLayout"><form class="sellerForm" onsubmit="event.preventDefault();submitSellerListing()"><div class="sectionhead"><div><span class="eyebrow darkey">SELLER DETAILS</span><h2>Your seller profile</h2></div></div><div class="twocol"><div class="field"><label>Display name</label><input id="sellerDisplay" required maxlength="120"></div><div class="field"><label>Phone</label><input id="sellerPhone" maxlength="40"></div></div><div class="field"><label>Location</label><input id="sellerLocation" required maxlength="160" placeholder="Lagos, Nigeria"></div><div class="sectionhead"><div><span class="eyebrow darkey">LISTING DETAILS</span><h2>What are you selling?</h2></div><span class="statuspill">PENDING MODERATION</span></div><div class="field"><label>Product title</label><input id="sellerTitle" required maxlength="160"></div><div class="field"><label>Category</label><select id="sellerCategory">'+cats+'</select></div><div class="field"><label>Description</label><textarea id="sellerDescription" required maxlength="2000" rows="6"></textarea></div><div class="twocol"><div class="field"><label>Price type</label><select id="sellerPriceMode"><option value="on_request">Price on request</option><option value="fixed">Fixed price</option><option value="negotiable">Negotiable</option></select></div><div class="field"><label>Price (NGN)</label><input id="sellerPrice" type="number" min="0" step="0.01"></div></div><div class="field"><label>Product photos</label><input id="sellerImages" type="file" accept="image/jpeg,image/png,image/webp" multiple required><small class="muted">1–8 images. Each image must be 10MB or smaller.</small></div><div id="sellerImagePreview" class="sellerPreviewGrid"></div><button class="btn red" type="submit">Submit listing for review →</button></form><aside class="sellerAside"><span class="eyebrow darkey">THE TWINS MODEL</span><h2>Trust before scale.</h2><p class="muted">Seller identity, listing media and moderation status live on the production server. Community listings remain separate from official Twins inventory.</p><div class="trustlist"><span>✓ Managed image storage</span><span>✓ Seller authentication</span><span>✓ Moderation queue</span><span>✓ Listing reports</span><span>✓ Verified payment flow</span></div></aside></div></section></main>'+foot()+'<div id="toast"></div>';
try{var p=await marketApi("/api/marketplace/seller/profile");if(p.profile){document.getElementById("sellerDisplay").value=p.profile.displayName||user.name||"";document.getElementById("sellerPhone").value=p.profile.phone||"";document.getElementById("sellerLocation").value=p.profile.location||""}}catch(e){document.getElementById("sellerDisplay").value=user.name||""}
document.getElementById("sellerImages").addEventListener("change",function(){var out=document.getElementById("sellerImagePreview");out.innerHTML="";Array.from(this.files||[]).slice(0,8).forEach(function(file){var r=new FileReader();r.onload=function(){out.insertAdjacentHTML("beforeend",'<img src="'+r.result+'" alt="">')};r.readAsDataURL(file)})});
}
async function submitSellerListing(){
var priceMode=document.getElementById("sellerPriceMode").value,price=document.getElementById("sellerPrice").value,files=Array.from(document.getElementById("sellerImages").files||[]);
if(priceMode==="fixed"&&(!price||Number(price)<=0)){toast("Enter a valid fixed price");return}
if(!files.length||files.length>8){toast("Choose 1–8 photos");return}
try{await marketApi("/api/marketplace/seller/profile",{method:"POST",body:JSON.stringify({displayName:document.getElementById("sellerDisplay").value.trim(),phone:document.getElementById("sellerPhone").value.trim()||null,location:document.getElementById("sellerLocation").value.trim()})});
var listing=(await marketApi("/api/marketplace/listings",{method:"POST",body:JSON.stringify({title:document.getElementById("sellerTitle").value.trim(),category:document.getElementById("sellerCategory").value,description:document.getElementById("sellerDescription").value.trim(),priceMode:priceMode,price:priceMode==="fixed"?Number(price):null,location:document.getElementById("sellerLocation").value.trim()})})).listing;
var form=new FormData();files.forEach(function(f){form.append("files",f,f.name)});await marketApi("/api/marketplace/listings/"+encodeURIComponent(listing.id)+"/media",{method:"POST",headers:{},body:form});location.href="seller-dashboard.html?saved=1";
}catch(e){toast(e.message||"Listing submission failed")}}
async function sellerDashboard(){
var root=document.getElementById("sellerdash");if(!root)return;var user=await currentAccount();if(!user){root.innerHTML=head()+'<main class="page"><div class="wrap"><div class="empty"><h2>Sign in required</h2><a class="btn red" href="login.html">Sign in / Create account</a></div></div></main>'+foot();return}
var list=[],profile=null,subscription=null,plans=[];try{list=(await marketApi("/api/marketplace/me")).listings||[]}catch(e){}try{profile=(await marketApi("/api/marketplace/seller/profile")).profile}catch(e){}try{subscription=(await marketApi("/api/marketplace/subscriptions/me")).subscription}catch(e){}try{plans=(await marketApi("/api/marketplace/plans")).plans||[]}catch(e){}try{analytics=(await marketApi("/api/marketplace/seller/analytics")).analytics}catch(e){}
var qs=new URLSearchParams(location.search),notice=qs.get("saved")?"Listing submitted for moderation.":(qs.get("payment")?"Payment returned. Status is confirmed from the server.":"");
root.innerHTML=head()+'<main class="page"><section class="section"><div class="wrap"><div class="sectionhead"><div><span class="eyebrow darkey">SELLER HUB</span><h1>Your marketplace workspace.</h1><p class="muted">Listings, seller status and membership are read from the production API.</p></div><a class="btn light" href="seller-analytics.html">Analytics →</a><a class="btn red" href="sell-on-twins.html">Create listing →</a></div>'+(notice?'<div class="panel"><b>'+marketSafe(notice)+'</b></div>':'')+'<div class="sellerKpis"><div><b>'+list.length+'</b><span>Your listings</span></div><div><b>'+marketSafe(profile?profile.verificationStatus:"pending")+'</b><span>Verification</span></div><div><b>'+marketSafe(subscription?subscription.status:"none")+'</b><span>Membership</span></div></div><section class="sellerPlans"><div class="sectionhead"><div><span class="eyebrow darkey">SELLER MEMBERSHIP</span><h2>Choose the commercial model.</h2></div></div><div class="grid">'+plans.map(function(p){return '<article class="planCard"><span class="eyebrow darkey">'+marketSafe(p.name)+'</span><h3>'+marketSafe(p.billing==="free"?"Free":"Monthly")+'</h3><p>'+marketSafe(p.features.join(" · "))+'</p><button class="btn '+(subscription&&subscription.plan===p.name&&subscription.status==="active"?"light":"red")+'" '+(p.billing!=="free"&&!p.configured?"disabled":"")+' onclick="startSellerPlan(\''+marketSafe(p.name)+'\')">'+(subscription&&subscription.plan===p.name&&subscription.status==="active"?"Active":(p.billing!=="free"&&!p.configured?"Not configured":"Choose plan"))+'</button></article>'}).join("")+'</div><p class="muted paymentnote">Paid plans use server-side Paystack initialization and webhook confirmation. No secret key is exposed in the browser.</p></section><section class="sectioninner"><h2>Your listings</h2>'+(list.length?'<div class="grid">'+list.map(function(x){var m=x.media&&x.media[0];return '<article class="card marketcard">'+(m?'<img src="'+marketSafe(m.url)+'" alt="'+marketSafe(x.title)+'" loading="lazy">':'<div class="sellerPreview"></div>')+'<div class="cardbody"><span class="realbadge">'+marketSafe(x.status)+'</span><h3>'+marketSafe(x.title)+'</h3><p class="muted">'+marketSafe(x.category)+' · '+marketSafe(x.location||"")+'</p><p>'+marketSafe(x.description)+'</p><b>'+marketMoney(x.price,x.currency)+'</b></div></article>'}).join("")+'</div>':'<div class="empty"><h3>No listings yet.</h3><a class="btn red" href="sell-on-twins.html">Create your first listing →</a></div>')+'</section></div></section></main>'+foot()+'<div id="toast"></div>';
}
async function startSellerPlan(name){try{var r=await marketApi("/api/marketplace/seller-plan",{method:"POST",body:JSON.stringify({plan:name})});if(r.payment&&r.payment.authorizationUrl){location.href=r.payment.authorizationUrl;return}toast("Membership activated");setTimeout(function(){location.reload()},600)}catch(e){toast(e.message||"Could not start membership payment")}}
if(page==="marketplace.html")marketplace();
if(page==="marketplace-listing.html")marketplaceListingPage();
if(page==="sell-on-twins.html")sellOnTwins();
if(page==="seller-dashboard.html")sellerDashboard();
