function marketSafe(v){return String(v==null?"":v).replace(/[&<>"]/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[c]})}
function marketplace(){
var root=document.getElementById("marketplace");
var cats=MARKETPLACE_CATEGORIES.map(function(c){return '<a class="marketcat" href="marketplace.html?category='+encodeURIComponent(c)+'"><b>'+marketSafe(c)+'</b><span>Browse community listings</span></a>'}).join("");
var saved=JSON.parse(localStorage.getItem("twins_marketplace_listings")||"[]");
var q=new URLSearchParams(location.search).get("category")||"";
var visible=saved.filter(function(x){return !q||x.category===q});
root.innerHTML=head()+
'<main class="page"><section class="marketHero"><div class="wrap marketHeroGrid"><div><span class="eyebrow">TWINS MARKETPLACE</span><h1>More than our own catalogue.</h1><p>Discover official Twins products and a separate community marketplace where approved sellers can submit their own products.</p><div class="heroactions"><a class="btn red" href="sell-on-twins.html">Sell on Twins →</a><a class="btn light" href="products.html">Shop official Twins stock</a></div></div><div class="marketTrust"><b>OFFICIAL TWINS</b><span>Our catalogue</span><b>COMMUNITY MARKET</b><span>Seller-submitted listings</span><b>MODERATED</b><span>Listings reviewed before publication</span></div></div></section>'+
'<section class="section"><div class="wrap"><div class="sectionhead"><div><span class="eyebrow darkey">EXPLORE</span><h2>Marketplace areas.</h2></div><p class="muted">Community listings are intentionally separated from official Twins inventory.</p></div><div class="marketcats">'+cats+'</div></div></section>'+
'<section class="section soft"><div class="wrap"><div class="sectionhead"><div><span class="eyebrow darkey">COMMUNITY LISTINGS</span><h2>'+(visible.length?"Your saved submissions":"No public community listings yet")+'</h2></div><a class="btn light" href="seller-dashboard.html">Seller Hub →</a></div>'+
(visible.length?'<div class="grid">'+visible.map(function(x){return '<article class="card marketcard"><img src="'+marketSafe(x.image||"assets/media/twins-commercial-equipment-showroom-02.jpg")+'" alt=""><div class="cardbody"><span class="realbadge">PENDING REVIEW</span><h3>'+marketSafe(x.title)+'</h3><p class="muted">'+marketSafe(x.category)+' · '+marketSafe(x.location)+'</p><p>'+marketSafe(x.description)+'</p><b>Price: '+marketSafe(x.price||"On request")+'</b></div></article>'}).join("")+'</div>':
'<div class="empty"><h2>The community side is ready for its first sellers.</h2><p class="muted">A browser-only listing is never treated as publicly live. Your submission stays in your seller workspace until production authentication, moderation and storage are connected.</p><a class="btn red" href="sell-on-twins.html">Create a seller listing →</a></div>')+
'</div></section>'+
'<section class="section"><div class="wrap marketSteps"><article><b>01</b><h3>Create</h3><p>Prepare your product, photos, description, location and price preference.</p></article><article><b>02</b><h3>Review</h3><p>Twins checks the listing before it can become publicly searchable.</p></article><article><b>03</b><h3>Discover</h3><p>Customers can browse community products separately from official Twins stock.</p></article><article><b>04</b><h3>Enquire</h3><p>Community purchases start enquiry-first until marketplace payments and buyer-protection services are activated.</p></article></div></section></main>'+foot()+'<div id="toast"></div>';
}
function sellOnTwins(){
var root=document.getElementById("sell");
var cats=MARKETPLACE_CATEGORIES.map(function(c){return "<option>"+marketSafe(c)+"</option>"}).join("");
root.innerHTML=head()+
'<main class="page"><section class="marketHero compact"><div class="wrap"><span class="eyebrow">SELL ON TWINS</span><h1>Turn your product into a proper listing.</h1><p>Twins Marketplace is a moderated seller layer, not an uncontrolled upload dump.</p></div></section>'+
'<section class="section"><div class="wrap sellerLayout"><form class="sellerForm" onsubmit="event.preventDefault();saveSellerListing()"><div class="sectionhead"><div><span class="eyebrow darkey">LISTING DETAILS</span><h2>Tell customers what you are selling.</h2></div><span class="statuspill">PENDING MODERATION</span></div><div class="field"><label>Product title</label><input id="sellerTitle" required maxlength="120" placeholder="e.g. 3-Group Commercial Coffee Machine"></div><div class="field"><label>Category</label><select id="sellerCategory">'+cats+'</select></div><div class="field"><label>Description</label><textarea id="sellerDescription" required maxlength="1200" rows="5" placeholder="Describe the product, condition, key details and what the buyer should know."></textarea></div><div class="twocol"><div class="field"><label>Price</label><input id="sellerPrice" placeholder="e.g. ₦450,000 or Price on request"></div><div class="field"><label>Seller location</label><input id="sellerLocation" required placeholder="Lagos, Nigeria"></div></div><div class="field"><label>Product photo</label><input id="sellerImage" type="file" accept="image/*" onchange="previewSellerImage(event)"><small class="muted">Prototype stores the preview locally. Production will upload media to managed storage.</small></div><img id="sellerPreview" class="sellerPreview" alt="Listing preview" hidden><button class="btn red" type="submit">Save listing for review →</button></form><aside class="sellerAside"><span class="eyebrow darkey">THE TWINS MODEL</span><h2>Trust before scale.</h2><p class="muted">Seller listings carry a clear community label. Official Twins products remain separate. Seller identity, reports, moderation and payment status belong on the production server.</p><div class="trustlist"><span>✓ Seller verification</span><span>✓ Listing moderation</span><span>✓ Report listing</span><span>✓ Separate official stock</span><span>✓ Payment gateway integration</span></div></aside></div></section></main>'+foot()+'<div id="toast"></div>';
}
function previewSellerImage(e){var file=e.target.files&&e.target.files[0];if(!file)return;var r=new FileReader();r.onload=function(){var el=document.getElementById("sellerPreview");el.src=r.result;el.hidden=false;window.__sellerImage=r.result};r.readAsDataURL(file)}
function saveSellerListing(){
var listing={id:Date.now(),title:document.getElementById("sellerTitle").value,category:document.getElementById("sellerCategory").value,description:document.getElementById("sellerDescription").value,price:document.getElementById("sellerPrice").value,location:document.getElementById("sellerLocation").value,image:window.__sellerImage||"",status:"Pending moderation",createdAt:new Date().toISOString()};
var list=JSON.parse(localStorage.getItem("twins_marketplace_listings")||"[]");list.unshift(listing);localStorage.setItem("twins_marketplace_listings",JSON.stringify(list));location.href="seller-dashboard.html?saved=1";
}
function sellerDashboard(){
var root=document.getElementById("sellerdash");
var list=JSON.parse(localStorage.getItem("twins_marketplace_listings")||"[]");
root.innerHTML=head()+
'<main class="page"><section class="section"><div class="wrap"><div class="sectionhead"><div><span class="eyebrow darkey">SELLER HUB</span><h1>Your marketplace workspace.</h1><p class="muted">This prototype stores listing drafts locally. Production publishing requires account authentication, moderation and server storage.</p></div><a class="btn red" href="sell-on-twins.html">Create listing →</a></div><div class="sellerKpis"><div><b>'+list.length+'</b><span>Saved listings</span></div><div><b>Pending</b><span>Moderation status</span></div><div><b>Separate</b><span>From official Twins stock</span></div></div><section class="sellerPlans"><div class="sectionhead"><div><span class="eyebrow darkey">SELLER MEMBERSHIP</span><h2>Choose the commercial model.</h2></div></div><div class="grid">'+MARKETPLACE_PLANS.map(function(p){return '<article class="planCard"><span class="eyebrow darkey">'+marketSafe(p[0])+'</span><h3>'+marketSafe(p[1])+'</h3><p>'+marketSafe(p[2])+'</p><p>'+marketSafe(p[3])+'</p><p>'+marketSafe(p[4])+'</p><button class="btn light" onclick="sellerPlanIntent(\''+marketSafe(p[0])+'\')">Choose plan</button></article>'}).join("")+'</div><p class="muted paymentnote">Payment activation is deliberately not faked in this static build. Production seller membership will use a verified gateway and server-side webhooks.</p></section><section class="sectioninner"><h2>Your listings</h2>'+
(list.length?'<div class="grid">'+list.map(function(x){return '<article class="card marketcard"><img src="'+marketSafe(x.image||"assets/media/twins-commercial-equipment-showroom-02.jpg")+'" alt=""><div class="cardbody"><span class="realbadge">'+marketSafe(x.status)+'</span><h3>'+marketSafe(x.title)+'</h3><p class="muted">'+marketSafe(x.category)+' · '+marketSafe(x.location)+'</p><p>'+marketSafe(x.description)+'</p></div></article>'}).join("")+'</div>':'<div class="empty"><h3>No listing drafts yet.</h3><a class="btn red" href="sell-on-twins.html">Create your first listing →</a></div>')+
'</section></div></section></main>'+foot()+'<div id="toast"></div>';
}
function sellerPlanIntent(name){localStorage.setItem("twins_seller_plan_intent",name);alert("Saved: "+name+". Production payment activation will be connected after the Twins merchant payment account is configured.");}
if(page==="marketplace.html")marketplace();
if(page==="sell-on-twins.html")sellOnTwins();
if(page==="seller-dashboard.html")sellerDashboard();
