(function(){
const root=document.getElementById("marketOps");if(!root)return;
const esc=v=>String(v==null?"":v).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const api=(p,o)=>apiRequest(p,o);
const money=(v,c="NGN")=>c==="NGN"?"₦"+Number(v||0).toLocaleString("en-NG"):c+" "+Number(v||0).toLocaleString();
let data={};
async function load(){
 try{const me=await api("/api/account/me");if(!me.user||!["admin","staff","owner"].includes(me.user.role))throw Error("Authorised staff access required");}
 catch(e){root.innerHTML='<main class="page"><div class="wrap"><div class="empty"><h2>Marketplace Operations</h2><p class="muted">'+esc(e.message)+'</p><a class="btn red" href="login.html">Sign in</a></div></div></main>';return}
 root.innerHTML=head()+'<main class="page"><section class="pagehead"><div class="wrap"><span class="eyebrow darkey">INTERNAL OPERATIONS</span><h1>Marketplace Operations</h1><p class="muted">Seller verification, listing moderation, reports, promotions, orders, disputes and marketplace analytics.</p><div class="herolinks"><a class="btn light" href="admin.html">Back to Admin</a><a class="btn red" href="marketplace.html">View Marketplace</a></div></div></section><section class="section"><div class="wrap"><div id="opsKpis" class="sellerKpis"></div><div class="panel"><div class="twocol"><div><label>Section</label><select id="opsSection" onchange="renderSection(this.value)"><option value="sellers">Sellers</option><option value="listings">Listings</option><option value="reports">Reports</option><option value="promotions">Promotions</option><option value="orders">Orders</option><option value="disputes">Disputes</option></select></div><div><label>Status filter</label><select id="opsFilter" onchange="refreshSection()"><option value="">All</option></select></div></div></div><div id="opsContent"></div></div></section></main>'+foot()+'<div id="toast"></div>';
 await refresh();
}
async function refresh(){data.overview=await api("/api/admin/marketplace/overview");const o=data.overview;document.getElementById("opsKpis").innerHTML=[["Sellers",o.sellers.total+" ("+o.sellers.pending+" pending)"],["Listings",o.listings.published+" live / "+o.listings.pending+" review"],["Reports",o.reports.open+" open"],["Orders",o.orders.total+" / "+money(o.orders.gross)],["Promotions",o.promotions.active+" active"]].map(x=>'<div><b>'+esc(x[1])+'</b><span>'+x[0]+'</span></div>').join("");await refreshSection();}
function filterOptions(s){const map={sellers:["pending","verified","rejected","suspended"],listings:["pending_review","published","rejected","paused","sold","archived"],reports:["open","reviewing","resolved","dismissed"],promotions:["draft","scheduled","active","paused","completed","cancelled"],orders:["requested","accepted","preparing","ready","completed","cancelled","disputed","refunded"],disputes:["open","reviewing","resolved","dismissed"]};document.getElementById("opsFilter").innerHTML='<option value="">All</option>'+(map[s]||[]).map(x=>'<option>'+x+'</option>').join("");}
function renderSection(s){filterOptions(s);refreshSection();}
async function refreshSection(){const s=document.getElementById("opsSection").value,f=document.getElementById("opsFilter").value;try{let d;if(s==="sellers")d=await api("/api/admin/marketplace/sellers"+(f?"?status="+encodeURIComponent(f):""));if(s==="listings")d=await api("/api/admin/marketplace/listings"+(f?"?status="+encodeURIComponent(f):""));if(s==="reports")d=await api("/api/admin/marketplace/reports"+(f?"?status="+encodeURIComponent(f):""));if(s==="promotions")d=await api("/api/admin/marketplace/promotions");if(s==="orders")d=await api("/api/admin/marketplace/orders"+(f?"?status="+encodeURIComponent(f):""));if(s==="disputes")d=await api("/api/admin/marketplace/disputes");data[s]=d;draw(s,d)}catch(e){document.getElementById("opsContent").innerHTML='<div class="empty"><p>'+esc(e.message)+'</p></div>'}}
function draw(s,d){let h="";if(s==="sellers")h='<div class="grid">'+d.sellers.map(x=>'<article class="card"><div class="cardbody"><span class="realbadge">'+esc(x.verificationStatus)+'</span><h3>'+esc(x.displayName)+'</h3><p class="muted">'+esc(x.location||"No location")+' · '+x.listingCount+' listings</p><p>'+esc(x.phone||"No phone")+'</p><div class="herolinks">'+["verified","rejected","suspended"].map(st=>'<button class="btn '+(st==="verified"?"red":"light")+' mini" onclick="verifySeller(\''+x.id+'\',\''+st+'\')">'+st+'</button>').join("")+'</div></div></article>').join("")+'</div>';
if(s==="listings")h='<div class="grid">'+d.listings.map(x=>'<article class="card"><div class="cardbody"><span class="realbadge">'+esc(x.status)+'</span><h3>'+esc(x.title)+'</h3><p class="muted">'+esc(x.seller)+' · '+esc(x.category)+'</p><p>'+x.mediaCount+' images · '+x.views+' views · '+x.contacts+' contacts · '+x.saves+' saves</p><b>'+money(x.price,x.currency)+'</b><div class="herolinks">'+["published","rejected","paused","sold","archived"].map(st=>'<button class="btn '+(st==="published"?"red":"light")+' mini" onclick="moderate(\''+x.id+'\',\''+st+'\')">'+st+'</button>').join("")+'</div></div></article>').join("")+'</div>';
if(s==="reports")h='<div class="grid">'+d.reports.map(x=>'<article class="card"><div class="cardbody"><span class="realbadge">'+esc(x.status)+'</span><h3>'+esc(x.listing)+'</h3><p><b>Seller:</b> '+esc(x.seller)+'<br><b>Reason:</b> '+esc(x.reason)+'</p><p class="muted">'+esc(x.details||"No details")+'</p><div class="herolinks">'+["reviewing","resolved","dismissed"].map(st=>'<button class="btn light mini" onclick="reportStatus(\''+x.id+'\',\''+st+'\')">'+st+'</button>').join("")+'</div></div></article>').join("")+'</div>';
if(s==="promotions")h='<div class="sectionhead"><div><h2>Promotion control</h2><p class="muted">Promotions are operational records only until Paystack billing is connected.</p></div></div><div class="grid">'+d.promotions.map(x=>'<article class="card"><div class="cardbody"><span class="realbadge">'+esc(x.status)+'</span><h3>'+esc(x.listing)+'</h3><p>'+esc(x.seller)+' · '+esc(x.placement)+'</p><p>'+esc(x.startsAt||"No start")+' → '+esc(x.endsAt||"No end")+'</p><b>'+money(x.budget)+'</b><div class="herolinks">'+["active","paused","completed","cancelled"].map(st=>'<button class="btn light mini" onclick="promoStatus(\''+x.id+'\',\''+st+'\')">'+st+'</button>').join("")+'</div></div></article>').join("")+'</div>';
if(s==="orders")h='<div class="grid">'+d.orders.map(x=>'<article class="card"><div class="cardbody"><span class="realbadge">'+esc(x.orderStatus)+'</span><h3>'+esc(x.reference)+'</h3><p><b>'+esc(x.listing)+'</b> · '+esc(x.seller)+'</p><p>Buyer: '+esc(x.buyerName)+' · '+esc(x.buyerPhone)+'</p><p>'+x.quantity+' × '+money(x.unitPrice,x.currency)+' + '+money(x.deliveryFee,x.currency)+'</p><b>Total '+money(x.total,x.currency)+'</b><p class="muted">Payment: '+esc(x.paymentStatus)+' — Paystack not connected.</p><div class="herolinks">'+["accepted","preparing","ready","completed","cancelled","refunded"].map(st=>'<button class="btn light mini" onclick="orderStatus(\''+x.id+'\',\''+st+'\')">'+st+'</button>').join("")+'</div></div></article>').join("")+'</div>';
if(s==="disputes")h='<div class="grid">'+d.disputes.map(x=>'<article class="card"><div class="cardbody"><span class="realbadge">'+esc(x.status)+'</span><h3>'+esc(x.reference)+'</h3><p>'+esc(x.listing)+' · '+esc(x.buyer)+'</p><p><b>'+esc(x.reason)+'</b></p><p class="muted">'+esc(x.details||"")+'</p><div class="herolinks">'+["reviewing","resolved","dismissed"].map(st=>'<button class="btn light mini" onclick="disputeStatus(\''+x.id+'\',\''+st+'\')">'+st+'</button>').join("")+'</div></div></article>').join("")+'</div>';
document.getElementById("opsContent").innerHTML=h||'<div class="empty">Nothing here yet.</div>';}
async function patch(path,body){await api(path,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});await refresh()}
async function verifySeller(id,status){await patch("/api/admin/marketplace/sellers/"+id+"/verification",{status})}async function moderate(id,status){await patch("/api/admin/marketplace/listings/"+id,{status})}async function reportStatus(id,status){await patch("/api/admin/marketplace/reports/"+id,{status})}async function promoStatus(id,status){await patch("/api/admin/marketplace/promotions/"+id,{status})}async function orderStatus(id,status){await patch("/api/admin/marketplace/orders/"+id,{status})}async function disputeStatus(id,status){await patch("/api/admin/marketplace/disputes/"+id,{status})}
window.renderSection=renderSection;window.refreshSection=refreshSection;window.verifySeller=verifySeller;window.moderate=moderate;window.reportStatus=reportStatus;window.promoStatus=promoStatus;window.orderStatus=orderStatus;window.disputeStatus=disputeStatus;load();})();