const {loadCatalogue,readExistingRules,computeMediaState}=require('./validator');
const {loadDiscoveryConfig}=require('./discovery/config');
const {createSearchProvider}=require('./discovery/sources');
const {fetchPage,probeImage,RateLimiter}=require('./discovery/fetch');
const {extractEvidence}=require('./discovery/extract');
const {matchProduct}=require('./discovery/matcher');
const {classifyMatch}=require('./discovery/scorer');
const {buildExistingUrlSet,checkDuplicate}=require('./discovery/dedupe');
function queryTerms(p){const n=String(p.n||'').trim();const q=['"'+n+'" product image','"'+n+'" manufacturer','"'+n+'" commercial equipment'];if(p.model)q.push('"'+p.model+'" "'+n+'"');if(p.capacity)q.push('"'+n+'" "'+p.capacity+'"');return [...new Set(q)];}
async function withConcurrency(items,limit,worker){const out=new Array(items.length);let cursor=0;async function run(){while(true){const i=cursor++;if(i>=items.length)return;out[i]=await worker(items[i],i);}}await Promise.all(Array.from({length:Math.min(limit,items.length)},run));return out;}
function pickImages(images){return images.filter(x=>!/(logo|icon|banner|placeholder|sprite|avatar)/i.test(x.url)).sort((a,b)=>Number(/json-ld|open-graph|product|gallery/i.test(b.source))-Number(/json-ld|open-graph|product|gallery/i.test(a.source)));}
async function discoverProduct(product,ctx){const found=[];for(const q of queryTerms(product).slice(0,ctx.config.maxQueriesPerProduct)){await ctx.rateLimiter.wait();let rows=[];try{rows=await ctx.provider.search(q,{count:ctx.config.maxResultsPerQuery,timeoutMs:ctx.config.timeoutMs});}catch(e){found.push({query:q,searchError:e.message,provider:ctx.provider.name});continue;}for(const r of rows||[]){if(!r.url||!/^https?:\/\//i.test(r.url)||found.some(x=>x.url===r.url))continue;found.push({...r});}}const evaluated=[];for(const c of found.filter(x=>x.url)){await ctx.rateLimiter.wait();const page=await fetchPage(c.url,{fetchImpl:ctx.fetchImpl,timeoutMs:ctx.config.timeoutMs,retries:ctx.config.retries,backoffMs:ctx.config.retryBackoffMs});if(!page.ok){evaluated.push({candidate:c,inaccessible:page.error,status:page.status});continue;}const evidence=extractEvidence(page.html,page.url);const imageCandidates=pickImages(evidence.images);let imageUrl='';let imageFailure='';for(const image of imageCandidates){const probe=await probeImage(image.url,{fetchImpl:ctx.fetchImpl,timeoutMs:ctx.config.timeoutMs});if(probe.ok){imageUrl=image.url;break;}imageFailure=probe.error;}const match=matchProduct(product,evidence);const classification=imageUrl?classifyMatch(match,evidence):{status:'UNRESOLVED',confidence:0,reason:imageFailure?'image inaccessible: '+imageFailure:'no trustworthy product image extracted'};if(!imageUrl){evaluated.push({candidate:c,evidence,match,classification});continue;}const dup=checkDuplicate(imageUrl,ctx.existingUrls,ctx.seenUrls);if(!dup.ok){evaluated.push({candidate:c,evidence,match,classification,duplicate:dup.reason});continue;}evaluated.push({candidate:c,evidence,match,classification,imageUrl:dup.url});}
const high=evaluated.filter(x=>x.classification?.status==='HIGH'&&x.imageUrl);const review=evaluated.filter(x=>x.classification?.status==='REVIEW'&&x.imageUrl);const best=high[0]||review[0];if(!best)return {productId:String(product.id),productName:String(product.n||''),status:'UNRESOLVED',confidence:0,candidate:null,reasons:['no acceptable candidate'],evaluated:evaluated.map(x=>({url:x.candidate?.url||'',query:x.query||'',status:x.classification?.status||'INACCESSIBLE',error:x.inaccessible||x.searchError||'',reason:x.classification?.reason||x.duplicate||x.searchError||''}))};ctx.seenUrls.add(best.imageUrl);return {productId:String(product.id),productName:String(product.n||''),status:best.classification.status,confidence:best.classification.confidence,candidate:{imageUrl:best.imageUrl||null,sourceUrl:best.candidate.url,sourceProvider:best.candidate.provider||ctx.provider.name,discoveredAt:ctx.discoveredAt,catalogueEvidence:{productId:String(product.id),name:String(product.n||''),category:String(product.c||''),type:String(product.type||product.productType||product.tag||''),capacity:String(product.capacity||''),model:String(product.model||''),specification:String(product.spec||'')},sourceEvidence:best.evidence.fields,imageEvidence:best.evidence.images,matching:best.match,reason:best.classification.reason},reasons:[best.classification.reason],evaluated:evaluated.map(x=>({url:x.candidate?.url||'',query:x.query||'',status:x.classification?.status||'INACCESSIBLE',error:x.inaccessible||x.searchError||'',reason:x.classification?.reason||x.duplicate||x.searchError||''}))};}
function buildProposal(results,state,config){return {schemaVersion:1,proposalType:'catalogue-wide-media-discovery',generatedAt:'deterministic-runtime',catalogue:{population:state.counts.catalogue,pendingAtStart:state.counts.pending},config:{provider:config.provider,concurrency:config.concurrency,maxQueriesPerProduct:config.maxQueriesPerProduct,maxResultsPerQuery:config.maxResultsPerQuery,timeoutMs:config.timeoutMs,retries:config.retries,retryBackoffMs:config.retryBackoffMs,requestsPerSecond:config.requestsPerSecond},results:results.slice().sort((a,b)=>Number(a.productId)-Number(b.productId))};}
async function discover(options={}){const data=options.data||loadCatalogue();const rules=options.rules||readExistingRules();const state=options.state||computeMediaState(data,rules);const config=options.config||loadDiscoveryConfig();const provider=options.provider||createSearchProvider(config,options.providers);const requestedIds=Array.isArray(options.productIds)?new Set(options.productIds.map(String)):null;const eligible=requestedIds?state.pending.filter(p=>requestedIds.has(String(p.id))):state.pending;const pending=eligible.slice(0,config.maxProducts>0?config.maxProducts:undefined);const ctx={config,provider,fetchImpl:options.fetchImpl||globalThis.fetch,existingUrls:buildExistingUrlSet(state),seenUrls:new Set(),rateLimiter:options.rateLimiter||new RateLimiter(config.requestsPerSecond),discoveredAt:options.discoveredAt||new Date().toISOString()};return buildProposal(await withConcurrency(pending,config.concurrency,p=>discoverProduct(p,ctx)),state,config);}
module.exports={queryTerms,withConcurrency,discoverProduct,buildProposal,discover};