const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {loadCatalogue,readExistingRules,computeMediaState}=require('../validator');const {discover,queryTerms}=require('../discovery');const {extractEvidence}=require('../discovery/extract');const {matchProduct}=require('../discovery/matcher');const {classifyMatch}=require('../discovery/scorer');const {checkDuplicate}=require('../discovery/dedupe');
const DATA=path.join(__dirname,'..','..','..','data.js');
function html(title,image,name=title,model='',capacity=''){return '<html><head><title>'+title+'</title><meta property="og:title" content="'+title+'"><meta property="og:image" content="'+image+'"></head><body><script type="application/ld+json">'+JSON.stringify({'@context':'https://schema.org','@type':'Product',name,model,image:[image]})+'</script><h1>'+name+'</h1><p>'+model+' '+capacity+'</p></body></html>';}
function provider(map){return {name:'fixture',async search(q){return (map[q]||[]).map(x=>({...x,provider:'fixture'}));}}}
function fetcher(pages){return async url=>pages[url]?{ok:true,status:200,url,text:async()=>pages[url],headers:{get:()=> 'text/html'}}:{ok:false,status:404,url};}
test('dynamic pending detection and existing mappings',()=>{const d=loadCatalogue(),s=computeMediaState(d,readExistingRules());assert.equal(s.counts.catalogue,530);assert.equal(s.counts.verified,226);assert.equal(s.pending.length,304);assert.ok(s.valid.length);});
test('query generation uses actual catalogue fields and future pending data',()=>{const q=queryTerms({id:999,n:'Test Oven',model:'T20',capacity:'20L'});assert.ok(q.some(x=>x.includes('Test Oven')));assert.ok(q.some(x=>x.includes('T20')));assert.ok(q.some(x=>x.includes('20L')));});
test('HIGH candidate',()=>{const p={n:'Planetary Mixer 20L',model:'B20',capacity:'20L'};const e=extractEvidence(html(p.n,'https://cdn.example/m.jpg',p.n,p.model,p.capacity),'https://example.test/p');assert.equal(classifyMatch(matchProduct(p,e),e).status,'HIGH');});
test('REVIEW candidate',()=>{const p={n:'Commercial Chest Freezer - Large'};const e=extractEvidence(html('Commercial Chest Freezer','https://cdn.example/f.jpg','Commercial Chest Freezer'),'https://example.test/p');assert.equal(classifyMatch(matchProduct(p,e),e).status,'REVIEW');});
test('UNRESOLVED candidate',()=>{const p={n:'Planetary Mixer 20L',capacity:'20L'};const e=extractEvidence(html('Office Chair','https://cdn.example/c.jpg','Office Chair'),'https://example.test/p');assert.equal(classifyMatch(matchProduct(p,e),e).status,'UNRESOLVED');});
test('duplicate and fabricated URL rejection',()=>{assert.equal(checkDuplicate('https://EXAMPLE.test:443/a.jpg#x',new Set(['https://example.test/a.jpg']),new Set()).ok,false);assert.equal(checkDuplicate('https://example.test/a.jpg',new Set(),new Set(['https://example.test/a.jpg'])).ok,false);assert.equal(checkDuplicate('not-a-url',new Set(),new Set()).ok,false);});
test('fabricated evidence is not accepted',()=>{const e=extractEvidence('<html><head><title>Empty</title></head><body></body></html>','https://example.test/p');assert.equal(e.fields.name,undefined);assert.equal(e.images.length,0);});
test('inaccessible source becomes UNRESOLVED',async()=>{const state={pending:[{id:1,n:'Unavailable Product'}],counts:{catalogue:1,pending:1},resolved:[],byId:new Map(),blocklist:{}};const r=await discover({state,config:{concurrency:1,maxQueriesPerProduct:1,maxResultsPerQuery:1,timeoutMs:10,retries:0,retryBackoffMs:0,requestsPerSecond:100},provider:{name:'fixture',async search(){return [{url:'https://example.test/blocked'}];}},fetchImpl:async()=>({ok:false,status:403}),discoveredAt:'2026-09-21T00:00:00Z'});assert.equal(r.results[0].status,'UNRESOLVED');assert.equal(r.results[0].evaluated[0].error,'forbidden');});
test('discovery does not mutate data.js and preserves legacy duplicates',async()=>{const before=fs.readFileSync(DATA,'utf8');const d=loadCatalogue(),s=computeMediaState(d,readExistingRules());const values=d.rawIdPairs.map(x=>x[1]);const counts=new Map();for(const v of values)counts.set(v,(counts.get(v)||0)+1);assert.ok([...counts.values()].some(x=>x>1));const p=s.pending[0],q=queryTerms(p)[0],page='https://fixture.example/p',img='https://fixture.example/i.jpg';await discover({state:{...s,pending:[p]},config:{concurrency:1,maxQueriesPerProduct:1,maxResultsPerQuery:1,timeoutMs:10,retries:0,retryBackoffMs:0,requestsPerSecond:100},provider:provider({[q]:[{url:page}]}),fetchImpl:fetcher({[page]:html(p.n,img)}),discoveredAt:'2026-09-21T00:00:00Z'});assert.equal(fs.readFileSync(DATA,'utf8'),before);});
test('deterministic rerun and newly added pending product',async()=>{const state={pending:[{id:999,n:'New Pending Product'}],counts:{catalogue:531,pending:1},resolved:[],byId:new Map([['999',{id:999,n:'New Pending Product'}]]),blocklist:{}};const q=queryTerms(state.pending[0])[0],page='https://fixture.example/new',img='https://fixture.example/new.jpg';const opts={state,config:{concurrency:1,maxQueriesPerProduct:1,maxResultsPerQuery:1,timeoutMs:10,retries:0,retryBackoffMs:0,requestsPerSecond:100},provider:provider({[q]:[{url:page}]}),fetchImpl:fetcher({[page]:html('New Pending Product',img)}),discoveredAt:'2026-09-21T00:00:00Z'};const a=await discover(opts),b=await discover(opts);assert.deepEqual(a,b);assert.equal(a.results[0].productId,'999');});