const API=(window.TWINS_API_BASE||"http://localhost:8000").replace(/\/$/,"");const $=id=>document.getElementById(id);let selected=[];let assets=[];
async function api(path,opts={}){const r=await fetch(API+path,{credentials:"include",...opts});let d={};try{d=await r.json()}catch{}if(!r.ok){const e=new Error(d.detail||"Request failed");e.status=r.status;throw e}return d}
function metadata(){return JSON.stringify({productId:$("productId").value.trim()||null,sourceType:$("sourceType").value,rightsStatus:$("rightsStatus").value,provenance:$("provenance").value.trim(),sourceUrl:$("sourceUrl").value.trim(),license:$("license").value.trim(),attribution:$("attribution").value.trim(),role:$("role").value})}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function renderSummary(d){$("summary").innerHTML='<div class="summary"><b>Batch '+d.batchId+'</b> · '+d.uploaded.length+' queued · '+d.duplicates.length+' exact duplicates · '+d.supportingDocuments.length+' supporting documents</div>'}
function render(){const q=$("search").value.toLowerCase(),s=$("status").value;const list=assets.filter(a=>(!s||a.status===s)&&(!q||a.filename.toLowerCase().includes(q)||(a.productId||"").toString().includes(q)));$("queue").innerHTML=list.length?list.map(a=>'<article class="asset-card"><div class="asset-thumb"></div><div class="asset-meta"><strong>'+escapeHtml(a.filename)+'</strong><span class="badge">'+escapeHtml(a.status)+'</span><small>Product: '+(a.productId||"Unassigned")+' · '+a.width+'×'+a.height+' · '+escapeHtml(a.sha256.slice(0,16))+'…</small><small>Rights: '+escapeHtml(a.rightsStatus)+' · Source: '+escapeHtml(a.sourceType)+'</small><small>'+escapeHtml(a.provenance||"No provenance recorded")+'</small></div><div class="actions"><input data-id="'+a.id+'" data-field="productId" value="'+(a.productId||"")+'" placeholder="Product ID"><input data-id="'+a.id+'" data-field="role" value="'+escapeHtml(a.role)+'" placeholder="role"><button class="btn light" data-action-id="'+a.id+'" onclick="updateAsset(this.dataset.actionId)">Save metadata</button><button class="btn light" data-action-id="'+a.id+'" onclick="revalidate(this.dataset.actionId)">Revalidate</button><button class="btn red" data-action-id="'+a.id+'" onclick="approveAsset(this.dataset.actionId)">Owner approve</button><button class="btn light" data-action-id="'+a.id+'" onclick="rejectAsset(this.dataset.actionId)">Reject</button></div></article>').join(""):'<div class="panel"><h3>No media assets match.</h3><p class="muted">Upload a batch or change the filters.</p></div>'}
async function refresh(){try{const d=await api("/api/admin/media?status="+encodeURIComponent($("status").value)+"&q="+encodeURIComponent($("search").value));assets=d.assets||[];render()}catch(e){$("queue").innerHTML='<div class="panel bad">'+escapeHtml(e.message)+'</div>'}}
async function updateAsset(id){const p=document.querySelector('[data-id="'+id+'"][data-field="productId"]'),r=document.querySelector('[data-id="'+id+'"][data-field="role"]');await api("/api/admin/media/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId:p.value.trim()||null,sourceType:$("sourceType").value,rightsStatus:$("rightsStatus").value,provenance:$("provenance").value.trim(),sourceUrl:$("sourceUrl").value.trim(),license:$("license").value.trim(),attribution:$("attribution").value.trim(),role:r.value})});await refresh()}
async function revalidate(id){await api("/api/admin/media/"+id+"/revalidate",{method:"POST"});await refresh()}
async function approveAsset(id){if(!confirm("Approve this asset? It will create a protected mapping but will not publish automatically."))return;await api("/api/admin/media/"+id+"/approve",{method:"POST"});await refresh()}
async function rejectAsset(id){if(!confirm("Reject this asset?"))return;await api("/api/admin/media/"+id+"/reject",{method:"POST"});await refresh()}
$("files").addEventListener("change",e=>{selected=[...e.target.files];$("uploadBtn").disabled=!selected.length;$("progressText").textContent=selected.length+" file(s) selected"});
$("dropzone").addEventListener("click",()=> $("files").click());
$("dropzone").addEventListener("dragover",e=>{e.preventDefault()});
$("dropzone").addEventListener("drop",e=>{e.preventDefault();selected=[...e.dataTransfer.files];$("uploadBtn").disabled=!selected.length;$("progressText").textContent=selected.length+" file(s) selected"});
$("uploadBtn").addEventListener("click",()=>{const fd=new FormData();selected.forEach(f=>fd.append("files",f));fd.append("metadata",metadata());const xhr=new XMLHttpRequest();xhr.open("POST",API+"/api/admin/media/upload");xhr.withCredentials=true;xhr.upload.onprogress=e=>{if(e.lengthComputable)$("progressText").textContent=Math.round(e.loaded/e.total*100)+"% uploading"};xhr.onload=async()=>{if(xhr.status>=200&&xhr.status<300){renderSummary(JSON.parse(xhr.responseText));$("progressText").textContent="Upload complete";selected=[];$("files").value="";$("uploadBtn").disabled=true;await refresh()}else $("progressText").textContent="Upload failed"};xhr.onerror=()=>$("progressText").textContent="Upload failed";xhr.send(fd)});
$("search").addEventListener("input",render);$("status").addEventListener("change",refresh);$("refresh").addEventListener("click",refresh);
(async()=>{try{const d=await api("/api/account/me");if(d.user.role!=="owner")throw new Error("Owner access required");$("identity").textContent=d.user.name+" · OWNER";$("app").classList.remove("hidden");await refresh()}catch(e){$("locked").classList.remove("hidden")}})();